version: '3'

services:
  alerter:
    image: 'firehouse/alerter-test'
    build: .
    environment:
      - logs_path=/logs
      - firehouse_path=/firehouse
      - BROADCAST_IP=
      - REDIS_HOST=
    user: vlc
    volumes:
      - ./logs:/logs:rw
      - ./firehouse:/firehouse:rw
    network_mode: "host"

  redis:
    image: 'redis:4-alpine3.8'
    ports:
      - "6379:6379"
    networks:
      - alerter-test

  redigo:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOST=
    ports:
      - "8081:8081"

networks:
  alerter-test:
    driver: bridge
